# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: adrian.ciu@codemart.ro
author_name: Adrian Ciu
has_binder: false
has_settings: false
kind: frontend
labextension_name: tvb-ext-rdc
project_short_description: A JupyterLab extension which wraps a given URL as an env
    variable.
python_name: tvb_ext_rdc
repository: https://github.com/the-virtual-brain/tvb-ext-rdc
test: false

