name: Mirror to Gitlab

on:
  push:
    branches: [ main ]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: syncmaster
        uses: wei/git-sync@v3
        with:
          source_repo: "the-virtual-brain/tvb-ext-rdc"
          source_branch: "main"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_2_0_SECRET }}@gitlab.ebrains.eu/ri/projects-and-initiatives/virtualbraintwin/tools/ext-rdc.git"
          destination_branch: "master"
      - name: synctags
        uses: wei/git-sync@v3
        with:
          source_repo: "the-virtual-brain/tvb-ext-rdc"
          source_branch: "refs/tags/*"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_2_0_SECRET }}@gitlab.ebrains.eu/ri/projects-and-initiatives/virtualbraintwin/tools/ext-rdc.git"
          destination_branch: "refs/tags/*"
